language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  python -m unittest
before_install:
  - pip install codecov
  - pip install coverage
after_success:
  - codecov
